name: AKS Integration Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "aks/**"
      - "testing/aks/**"
      - "testing/common/**"
      - "testing/charts/**"
      - "testing/prerequisites/**"

permissions:
  id-token: write # required for the Vault JWT/OIDC login below
  contents: read

jobs:
  test-aks:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      VAULT_ADDR: "https://vault.maas-vault-prod.solace.cloud:8200"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: testing/aks/go.sum

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Import Azure credentials from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: "${{ env.VAULT_ADDR }}"
          role: semi-automated-datacenter-cluster-ccrra-role
          method: jwt
          path: jwt-github
          jwtGithubAudience: https://github.com/SolaceDev
          secrets: |
            secret/data/development/azure client_id | ARM_CLIENT_ID
            secret/data/development/azure clientSecret | ARM_CLIENT_SECRET
            secret/data/development/azure tenant_id | ARM_TENANT_ID
            secret/data/development/azure subscription_id | ARM_SUBSCRIPTION_ID
            secret/data/development/azure subscription_id | TF_VAR_subscription

      - name: Download Go modules
        working-directory: ./testing/aks
        run: go mod download

      - name: Run AKS integration tests
        working-directory: ./testing/aks
        run: go test -v -timeout 90m -parallel 8 -run TestTerraformAksClusterComplete
